source 'https://rubygems.org'

gem 'json-ld', '>= 3.2.2'
gem 'json-ld-preloaded', '>= 3.2.1'
gem 'rdf-rdfa'
gem 'rdf-microdata'
gem 'rdf-reasoner'
gem 'rdf-turtle'
gem 'rspec'
gem 'rake'
gem 'nokogiri'
gem 'nokogumbo'
gem 'equivalent-xml'

group :debug do
  gem 'byebug'
end
